version: '3'
services:
  postgres:
    image: "postgres:alpine"
    environment:
     - POSTGRES_PASSWORD=root
     - POSTGRES_DB=mentions
    ports:
     - "5432:5432"
  migration:
    build:
      context: .
      dockerfile: Dockerfile_migration
      args:
        MIX_ENV: prod
    env_file:
     - docker_config/migration.env
    depends_on:
     - postgres
  mentions:
    build:
      context: .
      dockerfile: Dockerfile_worker
      args:
        MIX_ENV: prod
    restart: on-failure
    env_file:
     - docker_config/worker.env
    depends_on:
     - postgres
     - migration
  
