version: '3'
services:
  postgres:
    image: "postgres:alpine"
    environment:
     - POSTGRES_PASSWORD=root
    ports:
     - "5432:5432"
  migration:
    build:
      context: .
      dockerfile: Dockerfile_migration
    environment:
     - PG_DATABASE=mentions
     - PG_USERNAME=postgres
     - PG_PASSWORD=root
     - PG_HOSTNAME=postgres
    depends_on:
     - postgres
  mentions:
    build:
      context: .
      dockerfile: Dockerfile_worker
      args:
        MIX_ENV: prod
    restart: on-failure
    environment:
     - TWITTER_CONSUMER_KEY=
     - TWITTER_CONSUMER_SECRET=
     - TWITTER_ACCESS_TOKEN=
     - TWITTER_ACCESS_TOKEN_SECRET=
     - PG_DATABASE=mentions
     - PG_USERNAME=postgres
     - PG_PASSWORD=root
     - PG_HOSTNAME=postgres
     - PG_POOL_SIZE=10
     - MENTIONS_USERNAME=korn
     - MENTIONS_MAX_MENTIONS=100
    depends_on:
     - postgres
     - migration
  
